### ISSUE TITLE
nginx server out of date

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-assets#149]
While I was investigating other things, I stumbled across this "negative" report for arduino.cc:

> Outdated Web Server Nginx Found: nginx/1.4.2

According to: http://nginx.org/en/download.html

The "mainline" version is: nginx-1.7.7
The "stable" version is: nginx-1.6.2

**Comment by per1234** [comment]
Since Arduino Forum now uses [Discourse hosting](https://discourse.org/pricing) I think this is obsolete. If I'm wrong about that, please comment here and I'll investigate.
