### ISSUE TITLE
corrupt timezone file for Hawaii, HST.

### ISSUE THREAD

**Issue by matteosuppo** [arduino/forum-assets#184]
If you create a user and then select for Timezone [UTC-10:00] Hawaii, then the Forum web pages will be blank.  This is still not fixed.  I think this is a corrupt timezone file for Hawaii, HST.

**Comment by Bodmer** [comment]
Yes, I have been locked out of my account as I selected the Hawaii time zone by accident! I get PHP errors. Please fix!

**Comment by per1234** [comment]
I verified this no longer occurs.
