### ISSUE TITLE
AUTH0 random re-directs

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/forum-assets#289]
The issue is seeming random but very common throughout the forum user base.
Nobody is immune from the affect.

When performing an actions such as hitting the POST button you can be sent to the main forum page and are often left wondering of the post went through.
This means you have to re-navigate to the post concerned to check and if not the RE-post yet again.

This also affects when coming in from an email link also and some other aspects so is NOT limited to a single action.

Clearly this causes confusion and dissent among users and moderators alike as sometimes it also affects moderator actions.

See also https://forum.arduino.cc/index.php?topic=691954.0

**Comment by per1234** [comment]
I haven't experienced this or seen any reports of it since the migration to the Discourse framework and hosting in 2021 so I'll close this as resolved.

If anyone still experiences the fault, please comment here and I'll investigate.
