### ISSUE TITLE
Outages related to Cloudflare and AUTH0

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/forum-assets#294]
The use of cloudflare has not improved usage of the site and more especially the forum which continues to suffer regular outages.
The added use of AUTH0 also compounds issues with users getting to and from the forum.

Can the forum be ISOLATED from the above items to be allowed to operate more efficiently ?

**Comment by supernova-ws** [comment]
No.

**Comment by BallscrewBob** [comment]
Then what actions can be implemented to fix the issues ?

**Comment by per1234** [comment]
Closing as obsolete now that Arduino Forum uses Discourse Hosting.
