### ISSUE TITLE
Forum terribly slow/ not accessible

### ISSUE THREAD

**Issue by sterretjeToo** [arduino/forum-assets#390]
### Describe the problem

Since 2023/08/12 17:20 (SAST) it's near impossible to access the forum. 

ISP1
Windows 10, Chrome, clearing cookies/cache did not solve the issue.
Windows 10, Firefox, I did not attempt to clear.
Android, Chrome, same issue

ISP2
Android, Chrome, cleared cookies and can no longer login (I'm too impatient to wait for timeout).

Note that the browser always remembers my credentials so I don't gave to login each time that I  visit the forum.

Anybody else experiencing this?

Other sites work fine (including meta discourse.org).

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/forum-assets/issues?q=)
- [X] My report contains all necessary details

**Comment by sterretjeToo** [comment]
And obviously it came right after posting here, at least with ISP2. I will keep an eye on it.

**Comment by per1234** [comment]
Thanks @sterretjeToo/ I did experience some exceptionally long page load times earlier. It seems to be OK now.

There is a documented incident affecting the Discourse hosting service:

https://status.discourse.org/pages/incident/5e2141ce30dc5c04b3ac32fc/64d7b0543be636052e08ea31

**Comment by per1234** [comment]
Since the Discourse hosting service incident is marked as resolved and I haven't experienced any further degradations or seen any additional reports since I'll close this issue as resolved.

**Comment by sterretjeToo** [comment]
It indeed looks like all my devices and browsers don't experience problems any more; since 2021/08/13 05:30 SAST using ISP1. It might have been solved earlier but could only test it now.
