### ISSUE TITLE
Open external links in a new tab

### ISSUE THREAD

**Issue by ffissore** [arduino/forum-assets#71]
<a href="https://github.com/00alis"><img src="https://avatars.githubusercontent.com/u/6151328?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [00alis](https://github.com/00alis)**
_Thursday Oct 23, 2014 at 10:49 GMT_
_Originally opened as https://github.com/arduino/forum2/issues/71_

---

http://youtu.be/OLJG7t3zbJU
The above video shows an external link opening in the same page on the latest Firefox / Mac OS

**Comment by sterretjeToo** [comment]
The forum was completely reworked in 2021; is this still an issue?
